spring:
  application:
    name: enterprise-document-search
  profiles:
    active: production

  # Reactive WebFlux Configuration
  webflux:
    base-path: /api/v1
    static-path-pattern: /static/**
    format:
      date-time: iso

  # MySQL R2DBC Configuration
  r2dbc:
    url: r2dbc:mysql://mysql-primary:3306/document_search?useSSL=true&serverTimezone=UTC
    username: ${DB_USER:search_user}
    password: ${DB_PASSWORD:search_password}
    pool:
      initial-size: 20
      max-size: 100
      max-idle-time: 30m
      validation-query: SELECT 1
      acquire-retry: 3
      max-acquire-time: 60s

  # Redis Cluster Configuration
  data:
    redis:
      cluster:
        nodes:
          - redis-node-1:7001
          - redis-node-2:7002
          - redis-node-3:7003
          - redis-node-4:7004
          - redis-node-5:7005
          - redis-node-6:7006
        max-redirects: 3
      password: ${REDIS_PASSWORD:redis_cluster_password}
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 100
          max-idle: 20
          min-idle: 5
          max-wait: 2000ms
        cluster:
          refresh:
            adaptive: true
            period: 30s

    # Elasticsearch Configuration
    elasticsearch:
      repositories:
        enabled: true
      uris:
        - http://elasticsearch-node-1:9200
        - http://elasticsearch-node-2:9201
        - http://elasticsearch-node-3:9202
      username: ${ELASTIC_USER:elastic}
      password: ${ELASTIC_PASSWORD:elastic_password}
      connection-timeout: 10s
      socket-timeout: 30s

  # Jackson Configuration
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

  # File Upload Configuration
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
      file-size-threshold: 2MB

# Server Configuration
server:
  port: 8080
  error:
    include-stacktrace: never
    include-message: always
  compression:
    enabled: true
    mime-types: text/html,text/css,application/javascript,application/json
  http2:
    enabled: true
  netty:
    connection-timeout: 20s
    h2c-max-content-length: 0
    initial-buffer-size: 128KB
    max-chunk-size: 8KB
    max-initial-line-length: 4KB
    validate-headers: true

# Logging Configuration
logging:
  level:
    root: INFO
    com.enterprise.documentsearch: DEBUG
    org.springframework.data.elasticsearch: DEBUG
    org.springframework.data.r2dbc: DEBUG
    reactor.netty: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%X{traceId},%X{spanId}] %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%X{traceId},%X{spanId}] %logger{36} - %msg%n"
  file:
    name: /app/logs/document-search.log
    max-size: 100MB
    max-history: 30

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,env,configprops,httptrace,heapdump,loggers
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      show-components: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
        step: 10s
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5,0.75,0.9,0.95,0.99
    tags:
      application: ${spring.application.name}
      instance: ${HOSTNAME:localhost}

# Application Configuration
app:
  # JWT Configuration
  jwt:
    secret: ${JWT_SECRET:myVeryLongSecretKeyThatIsAtLeast256BitsLongForHS256Algorithm123456789}
    expiration: ${JWT_EXPIRATION:86400}  # 24 hours in seconds
    refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800}  # 7 days in seconds
    
  search:
    # Performance Configuration
    performance:
      max-concurrent-searches: 1000
      request-timeout: 500ms
      bulk-index-batch-size: 1000
      max-search-results: 10000
      
    # Cache Configuration
    cache:
      l1:
        type: caffeine
        max-size: 10000
        expire-after-write: 5m
        expire-after-access: 2m
      l2:
        type: redis-cluster
        expire-after-write: 30m
        key-prefix: "doc-search:"
        
    # Rate Limiting Configuration
    rate-limiting:
      enabled: true
      per-tenant:
        capacity: 1000
        refill-tokens: 100
        refill-period: 1s
      global:
        capacity: 5000
        refill-tokens: 500
        refill-period: 1s
        
    # Circuit Breaker Configuration
    circuit-breaker:
      failure-rate-threshold: 50
      slow-call-rate-threshold: 50
      slow-call-duration-threshold: 2s
      permitted-calls-in-half-open-state: 10
      sliding-window-size: 20
      minimum-calls: 10
      wait-duration-in-open-state: 10s
      
    # Security Configuration
    security:
      tenant-isolation: true
      max-file-size: 500MB
      allowed-file-types: pdf,doc,docx,txt,rtf,html,xml,json
      
    # Monitoring Configuration
    monitoring:
      metrics-enabled: true
      search-analytics: true
      performance-tracking: true
      slow-query-threshold: 1s

# Database Configuration
database:
  partitioning:
    enabled: true
    partition-by: tenant_id
    partition-count: 100
  connection-pool:
    minimum-idle: 10
    maximum-pool-size: 100
    idle-timeout: 600000
    max-lifetime: 1800000
    connection-timeout: 30000
    validation-timeout: 5000

# Elasticsearch Configuration
elasticsearch:
  cluster:
    name: document-search-cluster
    nodes: 3
  index:
    number-of-shards: 6
    number-of-replicas: 1
    refresh-interval: 1s
  search:
    max-concurrent-shard-requests: 5
    max-open-scroll-contexts: 500
    keep-alive: 5m

# Redis Configuration
redis:
  cluster:
    nodes: 6
    replicas: 3
  connection:
    timeout: 2000ms
    pool:
      max-total: 100
      max-idle: 20
      min-idle: 5

# Monitoring and Observability
monitoring:
  tracing:
    enabled: true
    sampling-rate: 0.1
  metrics:
    jvm: true
    system: true
    web: true
    database: true
    cache: true